### ISSUE TITLE
.jar

### ISSUE THREAD

**Issue by ChlckenWings** [TCDG/Elite-Developer-Discord-Bot#4]
when i run the .jar file the config file doesnt show up

**Comment by realshaunoneill** [comment]
@ChlckenWings Does it say anything else in the config?

**Comment by ChlckenWings** [comment]
there is no config

**Comment by ChlckenWings** [comment]
@XeliteXirish

**Comment by ChlckenWings** [comment]
so in instructions i go to a .jar file and the only one i see is in the gradle folder fight? and i double click it and nothing happens

**Comment by vladfrangu** [comment]
No, you must use a command prompt and type in `java -jar jarname.jar` where JarName is the name of the JAR file you got

**Comment by vladfrangu** [comment]
Then, the bot will generate a config file that you will drop your stuff in
